### PR TITLE
chore(deps): update deps PPS-179

### PR DESCRIPTION
**Pull request by Avantol13**
update deps to tackle PPS-179

### Dependency updates
- various updates to cryptography/future/pyjwt

### CODE REVIEW

**Comment by Avantol13** [comment]
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/alex/tmp/venv/fence/lib/python3.9/site-packages/markupsafe/__init__.py)
```

I **cannot** replicate this in Python 3.9.16 but I **can** replicate in 3.9.6 :face-palm:

**Review by paulineribeyre — APPROVED** [review]

**Review by paulineribeyre — APPROVED** [review]

**Comment by paulineribeyre** [comment]
we need to update `werkzeug` to >=2.2.3, but it depends on `MarkupSafe` >=2.1.1, which has been pinned to 2.0.1 to avoid the `soft_unicode` error

**Comment by paulineribeyre** [comment]
we need to update `werkzeug` to >=2.2.3, but `flask-sqlalchemy-session` does not work for `werkzeug` >= 2.1 (see [issue](https://github.com/dtheodor/flask-sqlalchemy-session/issues/14) and [unmerged fix](https://github.com/dtheodor/flask-sqlalchemy-session/pull/15))

**Comment by davidism** [comment]
> flask-sqlalchemy-session

If you also update to Flask-SQLAlchemy 3, you don't need this, it's the default behavior.

**Comment by paulineribeyre** [comment]
ignoring failing "CentralizedAuth" test which is currently broken and failing "Security Pipeline / Poetry_Vulnerabilities" check which will be addressed in a future PR

**Pull request merged**
